[workspace]

members = [
    "howitt",
    "howitt_derive",
    "howitt-cli",
    "howitt-dynamo",
    "howitt-fs",
    "howitt-graphql",
    "howitt-web",
    "howitt-web-lambda",
    "howitt-worker-lambda",
    "rwgps",
    "rwgps-types",
    "gtfs",
    "csaps",
]

resolver = "2"
