[workspace]

members = [
    "howitt",
    "howitt_derive",
    "howitt-cli",
    "howitt-fs",
    "howitt-postgresql",
    "howitt-web",
    "howitt-clients",
    "howitt-client-types",
    "rwgps",
    "rwgps-types",
    "gtfs",
    "csaps",
]

resolver = "2"
