[workspace]

members = [
    "howitt",
    "howitt-cli",
    "howitt-dynamo",
    "howitt-fs",
    "howitt-graphql",
    "howitt-web",
    "howitt-web-lambda",
    "howitt-worker-lambda",
    "rwgps",
    "rwgps-types",
    "gtfs"
]
