[package]
name = "howitt-postgresql"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
derive_more = { version = "1", features = ["full"] }
howitt = { path = "../howitt" }
howitt-observability = { path = "../howitt-observability" }
serde_json = "*"
uuid = "*"
itertools = "*"
thiserror = "*"
chrono = "*"
tokio-postgres = { version = "0.7.18", default-features = false, features = ["with-uuid-1", "with-chrono-0_4", "with-serde_json-1"] }
tokio = { version = "1", default-features = false, features = ["sync"] }
tracing = "0.1"
argon2 = "0.5.3"
chrono-tz = "0.10.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio-postgres = { version = "0.7.18", features = ["runtime"] }
postgres-native-tls = "0.5"
native-tls = "0.2"
tokio = { version = "1", features = ["rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio-postgres = { version = "0.7.18", default-features = false, features = ["js"] }

[dev-dependencies]
test-case = "3.1.0"
tokio = { version = "1", features = ["macros", "rt", "time"] }
geo = "*"
