apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: howitt
spec:
  rules:
  - host: howitt.haslehurst.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: howitt-webui
            port:
              number: 80
  - host: howitt-api2.haslehurst.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: howitt-web-api
            port:
              number: 80
