apiVersion: v1
kind: Service
metadata:
  labels:
    service: howitt-web-api
  name: howitt-web-api
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 8000
  selector:
    service: howitt-web-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: howitt-web-api
  name: howitt-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: howitt-web-api
  template:
    metadata:
      labels:
        service: howitt-web-api
    spec:
      containers:
        - image: ghcr.io/jacobh/howitt-web-api:main@${GITHUB_SHA}
          imagePullPolicy: Always
          name: howitt-web-api
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: howitt-db
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: howitt-db
                  key: REDIS_URL
            - name: AWS_REGION
              value: ap-southeast-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_SECRET_ACCESS_KEY
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
