[package]
name = "howitt"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "=2.0.20"
gpx = { version = "=0.10.0", features = ["use-serde"] }
geo = { version = "=0.33.1", features = ["serde"] }
derive_more = { version = "=2.1.1", features = ["full"] }
chrono = "=0.4.45"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151" }
itertools = "=0.15.0"
uuid = { version = "=1.26.1", features = ["serde", "v7"] }
anyhow = "=1.0.104"
async-trait = "=0.1.92"
bincode = "=1.3.3"
ulid = { version = "=1.1.4", features = ["serde"] }
md5 = "=0.8.1"
howitt_derive = { path = "../howitt_derive" }
rwgps_types = { path = "../rwgps-types" }
howitt_client_types = { path = "../howitt-client-types" }
howitt-observability = { path = "../howitt-observability" }
csaps = { path = "../csaps" }
futures = "=0.3.34"
ordered-float = "=5.5.0"
toml = "=0.8.19"
once_cell = "=1.21.4"
tokio = { version = "=1.53.1", features = ["rt", "sync"] }
either = { version = "=1.18.0", features = ["serde"] }
num = "=0.4.3"
url = { version = "=2.5.8", features = ["serde"] }
almost = "=0.2.0"
bytes = "=1.12.1"
argon2 = "=0.6.0"
jsonwebtoken = { version = "=9.3.0", default-features = false }
regex = "=1.13.1"
sanitize-filename = "=0.6.0"
tracing = "=0.1.44"
rustc-hash = "=2.1.3"

[dev-dependencies]
insta = { version = "=1.48.0", features = ["toml"] }
test-case = "=3.3.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "=1.12.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "=1.26.1", features = ["js"] }
getrandom = { version = "=0.2.15", features = ["js"] }
ring = { version = "=0.17.14", features = ["wasm32_unknown_unknown_js"] }
