[package]
name = "howitt_clients"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
howitt_client_types = { path = "../howitt-client-types" }
reqwest = { version = "=0.13.5", default-features = false, features = [
    "charset",
    "http2",
    "native-tls",
    "system-proxy",
] }
derive_more = { version = "=2.1.1", features = ["full"] }
async-trait = "=0.1.92"
url = "=2.5.8"
thiserror = "=2.0.20"
bytes = "=1.12.1"
redis = { version = "=1.7.0", features = ["aio", "tokio-comp"] }
object_store = { version = "=0.14.1", features = ["aws"] }
