[package]
name = "howitt_clients"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
howitt_client_types = { path = "../howitt-client-types" }
reqwest = "=0.12.12"
derive_more = { version = "=1.0.0", features = ["full"] }
async-trait = "=0.1.92"
url = "=2.5.4"
thiserror = "=2.0.11"
bytes = "=1.12.1"
redis = { version = "=0.28.1", features = ["aio", "tokio-comp"] }
object_store = { version = "=0.11.2", features = ["aws"] }
