[package]
name = "etrex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
gpx = "*"
geo = "*"
derive_more = "*"
chrono = "*"
kamadak-exif = "0.5.5"
fitparser = "0.5.1"
zip = "0.6.3"
