[package]
name = "mapbox-geocoding"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
reqwest = { version = "=0.13.5", default-features = false, features = [
    "charset",
    "http2",
    "json",
    "native-tls",
    "system-proxy",
] }
serde_urlencoded = "=0.7.1"
url = "=2.5.8"
