[package]
name = "gtfs"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
zip = "2"
csv = "1.1.6"
serde = { version = "1", features = ["derive"] }
