name = "howitt-webui"
main = "worker.ts"
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

routes = [
  { pattern = "howittplains.net", custom_domain = true }
]

[observability]
enabled = true

[observability.traces]
enabled = true

[build]
command = "bun run build"

[assets]
directory = "./build/client"

[vars]
API_BASE_URL = "https://api.howittplains.net"

[[services]]
binding = "API"
service = "howitt-web"
remote = true
