[package]
name = "howitt-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
apalis = { git = "https://github.com/geofmureithi/apalis.git", features = [
    "limit",
    "timeout",
] }
apalis-redis = { git = "https://github.com/geofmureithi/apalis.git" }
howitt = { path = "../../lib/howitt" }
howitt_clients = { path = "../../lib/howitt-clients" }
howitt_jobs = { path = "../../lib/howitt-jobs" }
howitt_client_types = { path = "../../lib/howitt-client-types" }
howitt-postgresql = { path = "../../lib/howitt-postgresql" }
tokio = { version = "1", features = ["full"] }
tracing = "*"
tracing-subscriber = "0.3"
image = { version = "*", default-features = false, features = [
    "rayon",
    "jpeg",
    "webp",
] }
webp = "*"
libwebp-sys = "*"
thiserror = "*"
rwgps = { path = "../../lib/rwgps" }
rwgps_types = { path = "../../lib/rwgps-types" }
