[package]
name = "howitt-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
apalis = { version = "0.6", features = ["limit", "timeout"] }
apalis-redis = { version = "0.6" }
howitt = { path = "../../lib/howitt" }
howitt_clients = { path = "../../lib/howitt-clients" }
howitt_client_types = { path = "../../lib/howitt-client-types" }
howitt-postgresql = { path = "../../lib/howitt-postgresql" }
tokio = { version = "1", features = ["full"] }
tracing = "*"
tracing-subscriber = "0.3"
image = { version = "*", default-features = false, features = [
    "rayon",
    "jpeg",
    "webp",
] }
webp = "*"
libwebp-sys = "*"
thiserror = "*"
rayon = "*"
