[package]
name = "howitt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
howitt = { path = "../../lib/howitt" }
howitt-postgresql = { path = "../../lib/howitt-postgresql" }
howitt_clients = { path = "../../lib/howitt-clients" }
howitt_client_types = { path = "../../lib/howitt-client-types" }
howitt_jobs = { path = "../../lib/howitt-jobs" }
anyhow = "*"
rayon = "*"
rwgps = { path = "../../lib/rwgps" }
rwgps_types = { path = "../../lib/rwgps-types" }
toml = "*"
serde_json = "*"
inquire = "*"
tokio = { version = "1", features = ["full"] }
gpx = "*"
itertools = "*"
prettytable-rs = "*"
ulid = "*"
chrono = "*"
uuid = { version = "*", features = ["v7"] }
chrono-tz = "*"
derive_more = { version = "*", features = ["full"] }
apalis = { git = "https://github.com/geofmureithi/apalis.git", features = [
    "limit",
    "timeout",
] }
apalis-redis = { git = "https://github.com/geofmureithi/apalis.git" }
mapbox-geocoding = { path = "../../lib/mapbox-geocoding" }
open-meteo = { path = "../../lib/open-meteo" }
serde_yaml = "0.9.34"
geo = "*"
serde = { version = "*", features = ["derive"] }
