[package]
name = "howitt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
howitt = { path = "../../lib/howitt" }
howitt-fs = { path = "../../lib/howitt-fs" }
howitt-postgresql = { path = "../../lib/howitt-postgresql" }
howitt_clients = { path = "../../lib/howitt-clients" }
howitt_client_types = { path = "../../lib/howitt-client-types" }
anyhow = "*"
rayon = "*"
rwgps = { path = "../../lib/rwgps" }
rwgps_types = { path = "../../lib/rwgps-types" }
toml = "*"
serde_json = "*"
inquire = "*"
tokio = { version = "1", features = ["full"] }
gpx = "*"
itertools = "*"
prettytable-rs = "*"
ulid = "*"
chrono = "*"
uuid = { version = "*", features = ["v7"] }
chrono-tz = "*"
derive_more = { version = "*", features = ["full"] }
apalis = { version = "0.6", features = ["limit", "timeout"] }
apalis-redis = { version = "0.6" }
