name: CDK Deployment

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production

        steps:
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: zstd libzstd-dev
                version: 1.0

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@nightly

            - name: Install Zig toolchain
              uses: korandoru/setup-zig@v1
              with:
                zig-version: 0.10.0

            - name: Install Cargo Lambda
              uses: jaxxstorm/action-install-gh-release@v1.9.0
              with:
                repo: cargo-lambda/cargo-lambda
                platform: linux
                arch: x86_64 # Other valid options for linux: 'aarch64'
            
            - name: Checkout
              uses: actions/checkout@v3

            - name: install cdk
              working-directory: cdk
              run: npm install

            # - name: build
            #   run: cargo lambda build

            - name: cdk synth
              working-directory: cdk
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: npm run cdk synth

            - name: cdk deploy
              working-directory: cdk
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: npm run cdk deploy
