name: Test

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Production

        env:
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Add PPA for libheif
              run: |
                sudo apt update
                sudo apt install -y software-properties-common
                sudo add-apt-repository -y ppa:strukturag/libheif
                sudo apt update

            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  **/target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: zstd libzstd-dev libheif-dev pkg-config zlib1g-dev
                version: 1.0

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@nightly

            - name: Test
              run: cargo test
