[package]
name = "howitt-web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["compression"] }
async-graphql = { version = "5", features = ["uuid"] }
async-graphql-warp = "5"
howitt-postgresql = { path = "../howitt-postgresql" }
howitt-graphql = { path = "../howitt-graphql" }
anyhow = "*"
