[package]
name = "howitt-web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
async-graphql = { version = "5", features = ["uuid"] }
async-graphql-warp = "5"
http = "*"
howitt = { path = "../howitt" }
howitt-fs = { path = "../howitt-fs" }
rwgps = { path = "../rwgps" }
anyhow = "*"
gpx = "*"
geo = "*"
geojson = "*"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = "*"